---
title: "Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
---

```{r, echo=FALSE}
# Checking enviroment
if(!exists("input") | !exists("threshold")) {
    cat("Error: No input or threshold set in enviroment")
    q("n")
    }
```

```{r, echo=FALSE}
dataset <- read.delim(input, header = F, sep = "\t", dec = ".", na.strings=c("", "na"))
colnames(dataset) <- c("Ref_scaf", "Position", "SNPs", "Frac", "Theta")
dataset$Theta[ dataset$Frac < threshold ] <- NA
NAwin <- sum(is.na(dataset$Theta))
win <- nrow(dataset) - NAwin
meanTheta <- mean(dataset$Theta, na.rm=T)
```

---

# Summary

File: `r input`

Fraction threshold: `r threshold`

Mean Waterson's theta: `r meanTheta`

Number of windows included: `r win`

Number of windows not included: `r NAwin`

---


# Whaterson's theta by window

```{r, echo=FALSE, warning=FALSE}
p <- ggplot(data=dataset) + 
    geom_line(aes(x=Position, y=Theta)) +
    # geom_point(aes(x=Position, y=Theta), size=5) + 
    geom_hline(aes(yintercept=meanTheta), col="red", linetype = "longdash") +
    facet_grid(~Ref_scaf, scales = "free_x") +
    labs(x="Chr. Position", y=expression(theta[w])) +
    theme_classic() #+ theme(text = element_text(size=18))
p
```


# SNP distribution in all windows

```{r, echo=FALSE, warning=FALSE}
p <- ggplot(data=dataset) + 
    geom_histogram(aes(x=SNPs), fill="white", col="black", binwidth = diff(range(dataset$SNPs))/30) +
    labs(x="Number of SNPs") +
    theme_classic() #+ theme(text = element_text(size=18))
p
```


# Fraction covered in all windows

```{r, echo=FALSE, warning=FALSE}
p <- ggplot(data=dataset) + 
    geom_histogram(aes(x=Frac), fill="white", col="black", binwidth = diff(range(dataset$Frac))/30) +
    geom_vline(aes(xintercept=threshold), col="red", linetype = "longdash") +
    labs(x="Frac. covered") +
    theme_classic() #+ theme(text = element_text(size=18))
p
```